services:
  # Service 1: Database PostgreSQL Lokal
  postgres:
    image: postgres:15-alpine
    container_name: ase_postgres
    restart: always
    environment:
      POSTGRES_USER: ase_admin
      POSTGRES_PASSWORD: ase_password_super_rahasia
      POSTGRES_DB: ase_laboratory_db
    ports:
      - "5432:5432" # Membuka port database agar bisa ditembak dari laptop Fedora kamu
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service 2: Aplikasi Next.js Standalone
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_web
    restart: always
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://ase_admin:ase_password_super_rahasia@postgres:5432/ase_laboratory_db
      - JWT_SECRET=${JWT_SECRET} # 👈 TAMBAHKAN INI (Mengambil nilai asli dari file .env VPS)
    depends_on:
      - postgres

volumes:
  postgres_data: # Data database aman tersimpan di VPS meskipun container restart